<?php

class SYarClientTest extends PHPUnit_Framework_TestCase
{
    private $host = '127.0.0.1';
    private $port = 9508;

    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = new \FSth\SYar\Client\Client($this->host, $this->port, 'TestService');
    }

    public function testClient()
    {
        for ($i = 0; $i < 4; $i++) {
            try {
                sleep(1);
                $result = $this->client->giveBack('hehe');
                var_dump($result);
            } catch (\Exception $e) {
                var_dump($e->getMessage());
            }
        }

    }
}